### ISSUE TITLE
npm install cherio && npm install array-filter doesn' work

### ISSUE THREAD

**Issue by captainjoh** [mrVragec/MMM-mvgmunich#1]
npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'cherio' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData cherio
8 silly fetchNamedPackageData cherio
9 silly mapToRegistry name cherio
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'cherio',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'cherio',
12 silly mapToRegistry   name: 'cherio',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/cherio
14 verbose request uri https://registry.npmjs.org/cherio
15 verbose request no auth needed
16 info attempt registry request try #1 at 23:21:49
17 verbose request id 7698a179c8456a16
18 verbose etag W/"563ce344-190"
19 verbose lastModified Fri, 06 Nov 2015 17:28:36 GMT
20 http request GET https://registry.npmjs.org/cherio
21 http 304 https://registry.npmjs.org/cherio
22 verbose headers { date: 'Fri, 05 May 2017 21:21:49 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"563ce344-190"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-hhn1525-HHN',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1494019310.995540,VS0,VE2',
22 verbose headers   vary: 'Accept-Encoding' }
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 05 May 2017 21:21:49 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"563ce344-190"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-hhn1525-HHN',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
23 silly get     'x-timer': 'S1494019310.995540,VS0,VE2',
23 silly get     vary: 'Accept-Encoding' } ]
24 verbose etag https://registry.npmjs.org/cherio from cache
25 verbose get saving cherio to /home/pi/.npm/registry.npmjs.org/cherio/.cache.json
26 verbose correctMkdir /home/pi/.npm correctMkdir not in flight; initializing
27 verbose stack TypeError: Cannot convert undefined or null to object
27 verbose stack     at pickVersionFromRegistryDocument (/usr/lib/node_modules/npm/lib/fetch-package-metadata.js:125:29)
27 verbose stack     at /usr/lib/node_modules/npm/node_modules/iferr/index.js:13:50
27 verbose stack     at /usr/lib/node_modules/npm/lib/utils/pulse-till-done.js:20:8
27 verbose stack     at saved (/usr/lib/node_modules/npm/lib/cache/caching-client.js:174:7)
27 verbose stack     at /usr/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:241:18
27 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
28 verbose cwd /home/pi/MagicMirror/modules/MMM-mvgmunich
29 error Linux 4.9.24-v7+
30 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "cherio"
31 error node v6.10.3
32 error npm  v3.10.10
33 error Cannot convert undefined or null to object

**Comment by mrVragec** [comment]
Please try to install '**cheerio**' instead of 'cherio'. I guess there was a typo in plugin name. Sorry for that and thanks for reporting your issue. 
Please, report if you will be able to solve the issue.
