### ISSUE TITLE
UNMET PEER DEPENDENCY stylelint invalid

### ISSUE THREAD

**Issue by lysid99** [mrVragec/MMM-mvgmunich#13]
I installed it, as told in you description but i get the following errors:
The mirror boots like normal, but does not show the MVG plan.

MM Version ## [2.1.3] - 2017-10-01
But tried with the newest also.
Hope you can help.

`pi@raspberrypi:~/MagicMirror $ npm install cheerio && npm install array-filter
magicmirror@2.1.3 /home/pi/MagicMirror
├── cheerio@1.0.0-rc.2 
└── UNMET PEER DEPENDENCY stylelint@7.13.0 invalid

npm WARN stylelint-config-recommended@1.0.0 requires a peer of stylelint@^8.0.0 but none was installed.
npm WARN stylelint-config-standard@17.0.0 requires a peer of stylelint@^8.0.0 but none was installed.
magicmirror@2.1.3 /home/pi/MagicMirror
├── array-filter@1.0.0 
└── UNMET PEER DEPENDENCY stylelint@7.13.0 invalid

npm WARN stylelint-config-recommended@1.0.0 requires a peer of stylelint@^8.0.0 but none was installed.
npm WARN stylelint-config-standard@17.0.0 requires a peer of stylelint@^8.0.0 but none was installed.
`

**Comment by lysid99** [comment]
And that's the error i get after updating MM to 2.2.2 via git pull && npm install.

Do you have any Idea?

pi@raspberrypi:~/MagicMirror $ npm install cheerio && npm install array-filter
magicmirror@2.2.2 /home/pi/MagicMirror
├─┬ cheerio@1.0.0-rc.2 
│ └─┬ parse5@3.0.3
│   └── @types/node@9.3.0 
├─┬ mocha-logger@1.0.5
│ └─┬ mocha@3.5.3 
│   ├─┬ commander@2.9.0 
│   │ └── graceful-readlink@1.0.1 
│   ├── debug@2.6.8 
│   ├── diff@3.2.0 
│   ├── glob@7.1.1 
│   ├── growl@1.9.2 
│   ├── json3@3.3.2 
│   ├─┬ lodash.create@3.1.1 
│   │ ├─┬ lodash._baseassign@3.2.0 
│   │ │ ├── lodash._basecopy@3.0.1 
│   │ │ └─┬ lodash.keys@3.1.2 
│   │ │   ├── lodash._getnative@3.9.1 
│   │ │   ├── lodash.isarguments@3.1.0 
│   │ │   └── lodash.isarray@3.0.4 
│   │ ├── lodash._basecreate@3.0.3 
│   │ └── lodash._isiterateecall@3.0.9 
│   ├─┬ mkdirp@0.5.1 
│   │ └── minimist@0.0.8 
│   └─┬ supports-color@3.1.2 
│     └── has-flag@1.0.0 
└── UNMET PEER DEPENDENCY stylelint@8.4.0

npm WARN grunt-stylelint@0.8.0 requires a peer of stylelint@^7.8.0 but none was installed.
magicmirror@2.2.2 /home/pi/MagicMirror
├── array-filter@1.0.0 
└── UNMET PEER DEPENDENCY stylelint@8.4.0

npm WARN grunt-stylelint@0.8.0 requires a peer of stylelint@^7.8.0 but none was installed.

**Comment by mrVragec** [comment]
Try to remove 'node_modules' and re-execute
`npm install &&npm install cheerio && npm install array-filter`
I just pull MagicMirror 2.2.2 and install mvgmunich without any issues. 

Let me know if you will succeed.

**Comment by lysid99** [comment]
Yes, that did the trick! Thank you.
In addition i had to add classes in the config.
`
classes: 'default',
`
