### ISSUE TITLE
MMM-mvgmunich plugin displays: undefined on Android full-screen browser fully

### ISSUE THREAD

**Issue by fl0wtec** [mrVragec/MMM-mvgmunich#14]
Dear @mrVragec,

the module is up and running on a rpi3 as server-only.

Accessing via Chrome browser (from PC or Android devices) displays everything as expected:
![image](https://user-images.githubusercontent.com/29065998/35405735-68794db0-0207-11e8-8eea-a6f49f671459.png)

However, using a variety of full-screen browsers on Android machines (eg. fully) just gives the module header and a "undefined" notification right underneath:
![image](https://user-images.githubusercontent.com/29065998/35405623-0b5e2498-0207-11e8-89a0-ae5aa6e64fb0.png)

On a side note: 
The compliments module as well never displayed on this browser. It did on any other browser though. Basically a very similar behavior which seems to be browser specific.

Any idea or hint what goes wrong with this specific browser?
Thanks!

**Comment by mrVragec** [comment]
Dear @fl0wtec, I'm sorry for my late answer. Would be possible to try with latest version from dev branch?
