### ISSUE TITLE
Format Time to Walk and Departure Time

### ISSUE THREAD

**Issue by MunichStef** [mrVragec/MMM-mvgmunich#17]
Currently Time to walk displays an absolute time when you should start walking and a relative time when the next u-bahn/s-bahn/bus/Tram/etc. departs.

I personally like it the other way round: absolute for departure, relative for when I need to go.

Hence my question: Would it be possible to have an option to configure both times being absolute or relative?

**Comment by mrVragec** [comment]
Yes, I think should not be a big deal to add this option as configuration property.

**Comment by mrVragec** [comment]
Hi MunichStef,

there is a new implementation done for your request. Would be possible for you to check 'dev' branch and give me feedback if it's what would you like to see as configurable?

**Comment by MunichStef** [comment]
Sorry, did not have the time recently to look into this. I'm just about to update my mirror again and will let you know. Thanks for the effort already!

**Comment by MunichStef** [comment]
works perfectly! Thanks!
