### ISSUE TITLE
Module doesn't appear/show

### ISSUE THREAD

**Issue by Da-ne-ezy** [mrVragec/MMM-mvgmunich#2]
Hi this is what I did:

1. git clone [https://github.com/mrVragec/MMM-mvgmunich.git](https://github.com/mrVragec/MMM-mvgmunich.git) in ~/MagicMirror/modules
2. Run: npm install cheerio && npm install array-filter in ~/MagicMirror/modules/MMM-mvgmunich
3. Add configuration block to my config.js:
```
{
  module: "mvgmunich",
  position: "bottom_left",
  header: "MVG",
    config: {
      haltestelle: "Hauptbahnhof",
      maxEntries: 25,   // 10 items on screen
      updateInterval: 60000,  // 60 s
      showUbahn: true,    //show ubahn route
      showBus: true,    // show bus route
      showTram: true,   // show tram route
      showSbahn: true   // show sbahn route
    }
},
```

The module does not appear on my screen. 
I tried to change the position to "top_right" but no changes.

Any ideas?

**Comment by mrVragec** [comment]
Yes, first install cheerio and array-filters in MagicMirror main folder not in MMM-mvgmunich (I don't know if it will make any difference, but let give a shot). Then rename module MMM-mvgmunich in mvgmunich (without 'MMM-').
 
After this, please try again and report progress.

**Comment by mrVragec** [comment]
Please change "Implerstrasse" to "Implerstraße" and should work. 
"Terofalstraße" should work without a problem.

**Comment by Da-ne-ezy** [comment]
Don't know why but "Terofalstraße" doesn't work for me.
All I see is the header!

**Comment by mrVragec** [comment]
Please, update MMM-mvgmunich plugin. Error handling was added and now you should see some error for "Terofalstraße". Please report the error or if it's working.

**Comment by Da-ne-ezy** [comment]
I get the following error on the display.
Station Terofalstra?e (yes with the "?" in it) is not correct, please update your config!
Hints for your station are:

**Comment by mrVragec** [comment]
Can you check what is the encoding of your config.js file? Which OS do you use?
Can you update me if "Implerstraße" is working for you? For me, it seems that there is a problem with encoding of config.js.

**Comment by Da-ne-ezy** [comment]
No "Implerstraße" doesn't work either. I think it's having a problem reading the "ß"-symbol because all other stations without "ß" are working fine.
What u mean by checking the encoding of my config.js file?
I'm using Magic Mirror Software v2.1.1!

**Comment by Da-ne-ezy** [comment]
Any ideas?

**Comment by mrVragec** [comment]
1. Is there any error on screen?
2. Which operating system do you use?
3. Do you get anything on the console?
4. Is there anything that you can see in developer tools ( Ctrl+Shift+I) of MagicMirror?

**Comment by Da-ne-ezy** [comment]
1. The only error I get when using "Implerstraße" is:  _Station Implerstra?e (yes with the "?" in it) is not correct, please update your config!_
2. I'm using Raspberry Pi 3 with Rasbian and Magic Mirror Software v2.1.1
3. No errors on the console itself.
4. Nothing

Like I said the problem is that my system can't read a "ß", thats why I'm getting errors. How can I change that?

**Comment by mrVragec** [comment]
1 Can you try if you can use "ß" in any other application? 
2. Which locale did you choose while installing raspberry pi?

**Comment by fl0wtec** [comment]
@Da-ne-ezy did you install "postcss-sass"?

Installing dependencies gave me a warning: "npm WARN postcss-html@0.11.0 requires a peer of postcss-sass@>=0.2.0 but none was installed."

So I did 
`npm install postcss-sass`

**Comment by mrVragec** [comment]
@Da-ne-ezy any updates on this issue? Solved or still persist?
