### ISSUE TITLE
Stations containing Umlauts are no more recognized

### ISSUE THREAD

**Issue by irinelturturea** [mrVragec/MMM-mvgmunich#20]
Hi
I updated the magic mirror to the latest version 
I tried the MVG module both from master and dev path.
Stations like Hauptbahnhof or Berg am Laim are fine but Süskindstraße

**Comment by mrVragec** [comment]
Hi irinelturturea,
I was able to reproduce the issue and find out what is wrong.
Fix will be available in next couple of days.

**Comment by mrVragec** [comment]
Hi @irinelturturea 
new version was release with fix for this bug. 
Please report if it solve your problem.

**Comment by irinelturturea** [comment]
> Hi @irinelturturea
> new version was release with fix for this bug.
> Please report if it solve your problem.

hi @mrVragec 
for me its still saying "name of the station not correct". I double checked with multiple stations.
Also I deleted the module completely and started with a new pull

**Comment by irinelturturea** [comment]
with the latest version the magic mirror opens as a blank screen.
As soon as I remove the mvgmunich from modules the rest seems to work fine even without updating the config file

**Comment by mrVragec** [comment]
> with the latest version the magic mirror opens as a blank screen.
> As soon as I remove the mvgmunich from modules the rest seems to work fine even without updating the config file

hi @irinelturturea 
would be possible to run `npm install urlencode` in main MagicMirror folder? 
There is one new dependency for the latest version of mvgmunich module which is not installed automatically.

**Comment by irinelturturea** [comment]
> > with the latest version the magic mirror opens as a blank screen.
> > As soon as I remove the mvgmunich from modules the rest seems to work fine even without updating the config file
> 
> hi @irinelturturea
> would be possible to run `npm install urlencode` in main MagicMirror folder?
> There is one new dependency for the latest version of mvgmunich module which is not installed automatically.

Seems to work now 
Thanks a lot

**Comment by irinelturturea** [comment]
Seems to work now after `npm install urlencode` 
Thanks a lot
