### ISSUE TITLE
Add "Xpressbus" as transport Type

### ISSUE THREAD

**Issue by MunichStef** [mrVragec/MMM-mvgmunich#23]
It would be great to get the option to seperate between an Express-Busline and a normal Busline. Alternatively you could add an option to ignore certain line numbers.

For excample at the Olympiaeinkaufszentrum I want to see departures of the X50 but not the other buslines...I still might be interested in the "normal" line 50 but that's less important.

**Comment by mrVragec** [comment]
@MunichStef would be possible to give me details where I can find express-Busline or is this just an example? 
From your proposal I understand something like POI (points of interests) for the transport items. So to have an option to filter out just the transports (line numbers) for which  you have interest.

**Comment by ipien** [comment]
I know this is an old thread but the express bus x50 stops for example at Olympia Einkaufszentrum West

![Screenshot_20191107-083242](https://user-images.githubusercontent.com/56938574/68368890-44f6a580-0139-11ea-99f5-cc1daf6f7301.jpg)

I have not checked yet it is working or not.
I will try tonight.

-------

I also have to say the idea of excluding single but lines or trams sound really good. That could certainly save some people a lot of time in comparison to putting in all the final destination names in the ignore list.

**Comment by mrVragec** [comment]
I agree that ignoring lines based on final destination is not a perfect solution. 
I also agree that ignoring lines based on line type and number (ex. U3, X50,...) is much more convenient, but in this case you ignore the lines in both directions. If I want to see U1 direction Olympiaeinkaufzentrum then I need to include U1 in both directions, or?

**Comment by mrVragec** [comment]
Hi @MunichStef,

I agree that ignoring lines based on line numbers should be implemented. So I tried to implement it in the most simple way as possible. There is a new map 'linesTo' which as a key can have 'exclude' or 'include' and values are line numbers. 
Example:
To **exclude** lines: `linesTo: {"exclude": ["U1", "U3"]},`
To **include** lines: `linesTo: {"include": ["U1", "U3"]},`

So now If you want to have only one line in the list then you can **include** only one line (no need to put all end stations in) and if you would like to exclude one line, you just need to change a key to exclude and add a line name which you would like to exclude. 

So an example for your config would be: 
`linesTo: {"include": ["U1", "U3", "X50"]},`

What is your opinion on this, you think might work?

You can test it in branch 'ignore_lines'.

**Comment by MunichStef** [comment]
hi @mrVragec,

to be honest I'd just have 2 variables "excludeLines" and "includeLines". Users should choose which one they want to use but could in theory use both of them. So I could either do:
`excludeLines: ["50, 60, 175, 163"]`
or
`includeLines: ["U1, U3, X50"]`

or you have a bit more complex structure but users cannot use include and exclude at the same time. this would be a problem if users accidentally use a line in both variables.

```
lineFiltering: {
"active": true, // set this to active if filtering should be used
"filterType": whitelist, // whitelist = only specified lines will be displayed, blacklist = all lines except specified lines will be displayed
"linenumbers": ["U1, U3, X50"] // lines that should be on the white-/blacklist} 
```

**Comment by mrVragec** [comment]
Hi @MunichStef,

my implementation took into consideration only the first item (excludedLines), so also if the user adds both they wouldn't have any effect. But I like your proposal better (it's more readable) so I will re-do the implementation.
