### ISSUE TITLE
Module does not load

### ISSUE THREAD

**Issue by thedoorsfanatic** [mrVragec/MMM-mvgmunich#25]
Since a couple of days your cool module does not load the stations anymore. Is there a problem with the API?

**Comment by mrVragec** [comment]
I just tried out my module (master branch) and MM (also master branch) and I got data for station Marienplatz. 
Would be possible to share configuration file and logs?

**Comment by thedoorsfanatic** [comment]
Hi, 
thanks for your response and excuse my bad English. I was able to solve the issue. See this post: https://forum.magicmirror.builders/topic/10610/public-transportation-module-munich-germany/3 and this issue I posted: https://github.com/vicmora/MMM-GoogleMapsTraffic/issues/30
