### ISSUE TITLE
Only 3 departures are shown

### ISSUE THREAD

**Issue by thedoorsfanatic** [mrVragec/MMM-mvgmunich#27]
Hi,

in my config file I wrote:
maxEntries: 6,

but only 3 departures are shown.

When don't use maxEntries at all it shows 4 departures.

What can I do to fix this?

**Comment by mrVragec** [comment]
Hi, 
as a first step would be possible to share your config file?

**Comment by thedoorsfanatic** [comment]
Hi,
thanks for your reply. That issue is solved. It was caused by another module: https://github.com/vicmora/MMM-GoogleMapsTraffic
Now your module works just fine

**Comment by mrVragec** [comment]
Ok, thank you for the update.
Closing the issue now.
