### ISSUE TITLE
no station name is working

### ISSUE THREAD

**Issue by cerberus82** [mrVragec/MMM-mvgmunich#30]
Hi Folks,
no matter which station name i put in the config file,
i always get
"The name of the station is not correct, please check on MVG."
tried at least 20 different stations which definitely exists.
same with default "Hauptbahnhof".

raspbian 9 (stretch)
MagicMirror 2.9.0

any ideas?

**Comment by cerberus82** [comment]
Thank you man!!!!!
You pointed in the right direction.
The guy responsible for the python wrapper you pointed to already figured out what changed.
obviously mvg indeed changed the urls...
to get it back working, open the mvgmunich.js
find the lines 18 & 19
within the link, simply swap positions of "api" and "fahrinfo"
-->  .../api/fahrinfo.....
and voila !
its working again!
thank you for pointing in the right direction !

**Comment by thedoorsfanatic** [comment]
Thanks, that worked for me, too!

**Comment by mrVragec** [comment]
@cerberus82 thank you for reporting the issue
@magic21nrw thank you for the pointing to the problem 
@all fix is available in the master branch
