### ISSUE TITLE
Showing 2 Stations

### ISSUE THREAD

**Issue by ipien** [mrVragec/MMM-mvgmunich#34]
Hello mrVragec,

I want to show two different stations.
One for me and one for my wife.

I was trying to load the module twice but then it shows the data for one station in both modules.
All the different settings how ever apply to both modules differently.

Also tried adding an array into the station field like [StationA, Station], but I guess this is not supported. So I also tried renaming everying in your module to mvgmunich2 but then this model will not start. 

My Linux and JavaScript skills are limited but I am not new to programming. I would be thankful for a little bit of direction. I am even willing to help developing if needed.

**Comment by mrVragec** [comment]
Hello @ipien,

this was already a problem in the past, which was successfully solved (issue #7). 
I will check again and try to fix it :).

**Comment by mrVragec** [comment]
Hi @ipien,

there is a new branch (name 'showing_2_stations') in which your problem should be solved. 
Would be possible to test it?

**Comment by ipien** [comment]
Thank you for looking into it so quickly.

Unfortunately it is not working for me.

I downloaded the "showing_2_station" branch with:
git clone --single-branch showing_2_stations ...

into my new MagicMirror folder then I copied my config.js from my backup there.

It shows me the same as before. Is there a way I can see if I downloaded the correct files?

I will try posting my config soon maybe I did something wrong there.

**Comment by ipien** [comment]
![IMG_0700](https://user-images.githubusercontent.com/56938574/68335516-e4397f80-00dc-11ea-9baa-e0778a679088.jpg)

If you prefer the text itself then I can copy this as well for you.
But for a quick check this should be fine.

**Comment by ipien** [comment]
I just noticed that I did not use your new code.

In the beginning if shows until the first update time for me 30 seconds - undefined

The it shows me the two different stations.
Thank you so much!

-------

But somehow not 100% correct. 
I have set the second station to show only tram and ubahn and I can see them but only 2 entries even though I selected 4 (maxentries)I guess this is new issue.
Total count with all different vehicle classes is probably 4.

**Comment by mrVragec** [comment]
Yes, there is a bug with counting shown stations :) Just saw it when testing your configuration, 
I will take care of it.

**Comment by ipien** [comment]
Thank you so much. You are doing a great job.

**Comment by mrVragec** [comment]
Hey @ipien, can you please pull from the branch 'showing_2_stations', the problem with number of visible stations should be solved.

**Comment by ipien** [comment]
Perfect thank you. Yes this is solved now!
And no error messages ;)
