### ISSUE TITLE
No data since last update

### ISSUE THREAD

**Issue by Kevinho195** [mrVragec/MMM-mvgmunich#40]
Hi,

I made the git pull request two days ago. Since then the great module does not show any connection. I see the header and my starting point. But then I only see "not defined".
Am I doing something wrong in my script?

{
			module: "mvgmunich",
			disabled: false,
			position: "bottom_left",
			header: "MVG",
		 	config: {
    				haltestelle: "St. Quirin Platz",
    				maxEntries: 4,             // 10 items on screen
    				updateInterval: 60000,      // 60 s
    				showIcons: true,            // Show transport type icon
    				transportTypesToShow: {
        				"ubahn": true,            // show ubahn route
        				"sbahn": true,            // show sbahn route
        				"bus": true,              // show bus route
        				"regional_bus": false,     // show regional bus route
        				"tram": false              // show tram route
    					},
    				ignoreStations: [],         // destination not to be shown
    				timeToWalk: 0,             // 10 min walking time to station. Default is 0
    				showWalkingTime: false,     // if the walking time should be included and the starting time is displayed
    				showTrainDepartureTime: true,     // show tran departure time
    				trainDepartureTimeFormat: "relative",   // format of the train departure time
    				walkingTimeFormat: "relative",    // format of the walking time
    				showInterruptions: true,
    				showInterruptionsDetails: true,
    				countInterruptionsAsItemShown: false
			 }
		},

**Comment by magic21nrw** [comment]
Same Problem here. Ran the git clone and npm install. Afterwards no data displayed.

I assume - we had this in the past - that there is a problem retrieving the data from the MVG-API. Is the link to the API correctly set with the new information?

**Comment by mrVragec** [comment]
Hi @Kevinho195,

could you please add:
```
lineFiltering: {
"active": false, 			// set this to active if filtering should be used
filterType": "whitelist", 	// whitelist = only specified lines will be displayed, blacklist = all lines except specified lines will be displayed
"lineNumbers": ["U1", "U3", "X50"] // lines that should be on the white-/blacklist
},
```
to yours configuration and let me know if it will work?

**Comment by Kevinho195** [comment]
Thanks for your quick response. It solved the problem!

**Comment by StefanMeGit** [comment]
Sorry, I have to open this issue again. It also doesn't work for me. 

```
{
			module: "mvgmunich",
			position: "top_right",
			header: "MVG",
			config: {
			    haltestelle: "Hermann-Gmeiner-Weg",
			    maxEntries: 10,             // 10 items on screen
			    updateInterval: 60000,      // 60 s
			    showIcons: true,            // Show transport type icon
			    transportTypesToShow: {
			        "ubahn": true,            // show ubahn route
			        "sbahn": true,            // show sbahn route
			        "bus": true,              // show bus route
			        "regional_bus": true,     // show regional bus route
			        "tram": true              // show tram route
			    },
			    ignoreStations: [],         // destination not to be shown
			    timeToWalk: 0,             // 10 min walking time to station. Default is 0
			    showWalkingTime: false,     // if the walking time should be included and the starting time is displayed
			    showTrainDepartureTime: true,     // show tran departure time
			    trainDepartureTimeFormat: "absolute",   // format of the train departure time
			    walkingTimeFormat: "relative",    // format of the walking time
			    showInterruptions: true,
			    showInterruptionsDetails: true,
    			countInterruptionsAsItemShown: true,
    			}
			}
```
