### ISSUE TITLE
"Bus" symbol also for regional busses

### ISSUE THREAD

**Issue by charraeus** [mrVragec/MMM-mvgmunich#41]
It would be nice if you could add the "bus"-symbol which you use for the mvg-busses,  also for the regional busses.
![IMG_0920](https://user-images.githubusercontent.com/38609969/71321704-db024780-24bd-11ea-8c8d-9fc2824308b8.jpg)

Thank's a lot und frohe Feiertage.

**Comment by mrVragec** [comment]
Hi @charraeus,
thank you for reporting this issue. 
There is a new branch 'regional_busses_icon' which should fix problem with icons.

Feel free to test it

**Comment by charraeus** [comment]
Servus @mrVragec,
I have tested the branch today. It works :-). 
Vielen Dank und ein gutes neues Jahr 2020.
