### ISSUE TITLE
Keine Anzeige mit Haltestell "Münchner Str./Würmkanal, Karlsfeld (Obb."

### ISSUE THREAD

**Issue by glanghei** [mrVragec/MMM-mvgmunich#48]
Hallo Simon, Ich bekomme keine Anzeige mit der Verbindungen mit folgenen Einstellungen:

{
                        module: "mvgmunich",
                        position: "top_center",
                        header: "MVG",
                        config: {
                                haltestelle: "Münchner Str./Würmkanal, Karlsfeld (Obb.)",
                                maxEntries: 5,             // 10 items on screen
                                updateInterval: 60000,      // 60 s
                                showIcons: true,            // Show transport type icon
                                transportTypesToShow: {
                                        "ubahn": true,            // show ubahn route
                                        "sbahn": true,            // show sbahn route
                                        "bus": true,              // show bus route
                                        "regional_bus": false,     // show regional bus route
                                        "tram": false              // show tram route
                                },
                                ignoreStations: [],         // destination not to be shown
.

.
.
.
.
![myMagicMirror](https://user-images.githubusercontent.com/22743296/120750390-95490b80-c506-11eb-903b-b5561a87e27f.png)

Hast du eine Tipp für mich.
Danke - Günter

**Comment by mrVragec** [comment]
Hallo Günter, 

mit der folgenden config bekomme ich Bus 172.
```
{
        module: "mvgmunich",
        position: "top_center",
        header: "MVG",
        config: {
                haltestelle: "Münchner Str./Würmkanal, Karlsfeld (Obb.)",
                maxEntries: 5, // 10 items on screen
                updateInterval: 60000, // 60 s
                showIcons: true, // Show transport type icon
                transportTypesToShow: {
                        "ubahn": true, // show ubahn route
                        "sbahn": true, // show sbahn route
                        "bus": true, // show bus route
                        "regional_bus": true, // show regional bus route
                        "tram": false // show tram route
                },
                ignoreStations: [],         // destination not to be shown
                timeToWalk: 0,             // 10 min walking time to station. Default is 0
                showWalkingTime: false,     // if the walking time should be included and the starting time is displayed
                showTrainDepartureTime: true,     // show tran departure time
                trainDepartureTimeFormat: "relative",   // format of the train departure time
                walkingTimeFormat: "relative",    // format of the walking time
                lineFiltering: {
                        active: false,
                        filterType: "whitelist",
                        lineNumbers: []
                }
        }
}
```

Kannst du mir bitte deine ganze config für mvgmunich geben?

LG Simon

**Comment by glanghei** [comment]
Wie gewünscht meine Configdatei.

[myMVGMunich.cfg.txt](https://github.com/mrVragec/MMM-mvgmunich/files/6643842/myMVGMunich.cfg.txt)
