### ISSUE TITLE
S-bahn problem

### ISSUE THREAD

**Issue by irinelturturea** [mrVragec/MMM-mvgmunich#5]
Hi
There seems to be a problem related to s bahns. with the following configuration it displays everything except s-bahns. The problem reproduces for other stations as well. I believe something has changed at MVG side. It seems sbahn is treated differently than the rest. 

{
  module: "mvgmunich",
  position: "top_bar",
  header: "MVG",
    config: {
      haltestelle: "Hauptbahnhof",
      maxEntries: 10,   // 10 items on screen
      updateInterval: 60000,  // 60 s
      showUbahn: true,    //show ubahn route
      showBus: true,    // show bus route
      showTram: true,   // show tram route
      showSbahn: true   // show sbahn route
    }
},

**Comment by irinelturturea** [comment]
seems to work now

**Comment by irinelturturea** [comment]
Hi
I believe the fix for this or for the next ticket added an instability.
Basically every few hour my raspberry pi zero blocks completely, there is no more magic mirror update on the screen and no answer on SSH.
I removed the MVG configuration from the config file and it seems stable again.

I have not tried yet with a keyboard connected directly to see it its still responsive or not. I will try this evening and report back

**Comment by mrVragec** [comment]
Hi, 
yes, it's true. Thank you for reporting. Lucky you ... my rPI freezes after 2 min :). 
Please check the latest update on 'dev' branch, with it my rPI don't freeze any more (not for last 30 min).
I will merge code tomorrow, just want to be sure rPI won't freeze over night.

**Comment by irinelturturea** [comment]
Hi
I will try this evening the dev path unless you merge back on the main line by then :)

**Comment by irinelturturea** [comment]
It seems to work now. It ran the complete night without any problems
