### ISSUE TITLE
MMM-mvgmunich module pulls no data

### ISSUE THREAD

**Issue by lobr95** [mrVragec/MMM-mvgmunich#51]
Hello,

even after installing and configuring the module according the github readme section, the module is displayed at the magic mirror page, but pulls no data (see screenshot).

![Capture](https://user-images.githubusercontent.com/49557314/147986093-bdf43f7f-aa0e-42ba-8623-369563b9faf6.PNG)

No errors have been thrown into the error log.

**Comment by spld3rrr** [comment]
I got the same issue. It recognices the station, but doesn't show any information..

**Comment by mrVragec** [comment]
Hello @s-blottk, @spld3rrr,

could you please share the configuration and at the same time:
- check the version of the MagicMirror
- check the version of the MMM-mvgmunich plugin
- check the version of NPM
- try to reinstall all the modules

Best regards,
Simon

**Comment by spld3rrr** [comment]
Thanks for your response. After going through the error-logs I found out it was missing the module 'request'. After uning `npm install request` in modul mvgmunich it now shows the departing lines.

Best regards,
Alex
