### ISSUE TITLE
Undefined Error

### ISSUE THREAD

**Issue by wiesty** [mrVragec/MMM-mvgmunich#52]
Everytime I am trying to fetch any data it says undefined (even with the standard config template given in your repo)

Internet working (can fetch other apis etc.)
node latest version
Running on docker bastilimbach/docker-magicmirror

I don't know if they changed their API but it is still working with station id's...
Thanks

**Comment by SiDuMo1** [comment]
same issue here, seems to be unfixed :(

**Comment by pyphysics** [comment]
same here...

**Comment by wiesty** [comment]
> same issue here, seems to be unfixed :(

made a own module for mvg. Would be happy if you could test it and tell me any bugs :)

**Comment by SiDuMo1** [comment]
Will do! Danke :)

Von: Bastian ***@***.***>
Gesendet: Mittwoch, 1. März 2023 18:07
An: mrVragec/MMM-mvgmunich ***@***.***>
Cc: SiDuMo1 ***@***.***>; Comment ***@***.***>
Betreff: Re: [mrVragec/MMM-mvgmunich] Undefined Error (Issue #52)


same issue here, seems to be unfixed :(

made a own module for mvg. Would be happy if you could test it and tell me any bugs :)

-
