### ISSUE TITLE
multiple stations

### ISSUE THREAD

**Issue by irinelturturea** [mrVragec/MMM-mvgmunich#7]
hi 
When configuring multiple stations the content for the same station is displayed for all configured stations
Except the name of the station the displayed content is identical
![mvgmunich](https://user-images.githubusercontent.com/33999597/33431386-749dbf0e-d5d4-11e7-8a68-f75b08c838af.jpg)

**Comment by mrVragec** [comment]
Hi irinelturturea, 
please check latest release and please report if working. 

![image](https://user-images.githubusercontent.com/2029195/33500522-5d4bbc10-d6d9-11e7-938b-bc5f8ad5fa84.png)

**Comment by irinelturturea** [comment]
Looks good☺️
Thx.
